name: Maven Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Private repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: palace
          server-username: REPO_USERNAME_REF
          server-password: REPO_TOKEN_REF

      - name: Build with Maven
        run: mvn -B clean package
        env:
          REPO_TOKEN_REF: ${{ secrets.REPO_TOKEN }}
          REPO_USERNAME_REF: ${{ secrets.REPO_USERNAME }}

      - name: Package artifacts
        run: mkdir staging && cp target/*.jar staging

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Plugin Jar
          path: staging
